default:
  api_login_id: 5Ldj59bGu
  api_transaction_key: 94Awp2dVh8994C3F
  merchant_hash_value: 76STRYsdsffge@#$asdr@
  error_url: http://ec2-54-200-141-93.us-west-2.compute.amazonaws.com/authorize_payment/error
  receipt_url: http://ec2-54-200-141-93.us-west-2.compute.amazonaws.com/authorize_payment/receipt
  relay_response_url: http://ec2-54-200-141-93.us-west-2.compute.amazonaws.com/authorize_payment/relay_response

development: 
 # <<: *default
test: 
  #<<: *default
production: 
  #<<: *default